# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://m8ttyb.github.io/"
title: SecretMustache
copyright: "© [m8ttyb](https://github.com/m8ttyB/)"
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["blog", "about"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Blog
          url: blog/
          weight: 1
        - name: About
          url: about
          weight: 2
        - name: Tags
          url: tags/
          weight: 10
        - name: WiKi
          url: https://github.com/m8ttyB/m8ttyb.github.io/wiki

    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: English
      profileMode:
        title: Matt Brandt
        enabled: true
        imageUrl: "images/avatar.jpg"
        imageTitle: ProfileMode image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "Open Source | Software Engineer | Engineering Manager"

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: "Matt Brandt" # default author

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false # disable share buttons located in footer of each post
  ShowReadingTime: true
  # disableSpecial1stPost: true #
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  images: ["images/papermod-cover.png"]

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/m8ttyB"
    - name: LinkedIn
      title: View LinkedIn Profile
      url: "https://www.linkedin.com/in/mlbrandt/"
    - name: BlueSky
      title: BlueSky
      url: "https://bsky.app/profile/m8ttyb.bsky.social"
    # - name: KoFi
    #   title: Buy me a Ko-Fi :)
    #   url: "https://ko-fi.com/adityatelange"

  editPost:
    URL: "https://github.com/m8ttyb/m8ttyb.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
